hosts:
  - name: Zues
    host: ssh://zues
  - name: Sidecar
    host: ssh://sidecar
  - name: Frigate
    host: ssh://nvr
  - name: Recipinned
    host: ssh://recipinned
  - name: Gitea Runner
    host: ssh://gitea
columns:
  - status
  - name
  - host
  - cpu
  - memory
  - net_tx
  - net_rx
  - uptime
sort: uptime
sort_direction: desc
all: false
