# https://taskfile.dev

version: "3"

vars:
  MMDOT_CMD: mmdot --log-level=info

tasks:
  fmt:
    desc: formats neovim files
    cmds:
      - stylua --config-path="./.config/nvim/stylua.toml" ./.config/nvim/

  xcode:
    desc: setups software update and enables xcode
    cmds:
      - sudo softwareupdate -i -a
      - xcode-select --install || true
      - sudo xcodebuild -license accept

  setup:
    desc: runs pre-setup steps for dotfiles configuraton
    cmds:
      - chmod +x ./bin/*
      - chmod +x ./setup/*.sh
      - chmod +x ./files/bootstrap.sh
      - ./files/bootstrap.sh
      - mise install

  stow:
    desc: runs stow command with arguments
    cmds:
      - stow -t ~/ .


  # ---------------------------------------------------------
  ## mmdot

  encrypt:
    desc: encrypt vault using mmdot
    cmds:
      - "{{ .MMDOT_CMD }} encrypt"

  decrypt:
    desc: encrypt vault using mmdot
    cmds:
      - "{{ .MMDOT_CMD }} decrypt"

  run:
    desc: run mmdot run
    cmds:
      - "{{ .MMDOT_CMD }} run {{ .CLI_ARGS }}"
