- name: Set env.local File
  template:
    src: env.local.j2
    dest: "{{ secrets_env_local_file }}"
    owner: "{{ main_user }}"
    group: "{{ main_group }}"
    mode: 0644
  when: secrets_env_local is defined and secrets_env_local | length > 0
