---
dev_dir: "{{ user_home }}/code"

git_username: "Hayden"
git_email: "64056131+hay-kot@users.noreply.github.com"
git_global_ignore_file: "{{ user_home }}/.gitignore_global"
git_global_ignore_content: |
  # An example global gitignore file
  #
  # Place a copy if this at ~/.gitignore_global
  # Run `git config --global core.excludesfile ~/.gitignore_global`

  # Compiled source #
  ###################
  *.com
  *.class
  *.dll
  *.exe
  *.o
  *.so
  *.pyc
  *.pyo

  # Packages #
  ############
  # it's better to unpack these files and commit the raw source
  # git has its own built in compression methods
  *.7z
  *.dmg
  *.gz
  *.iso
  *.jar
  *.rar
  *.tar
  *.zip
  *.msi

  # Logs and databases #
  ######################
  *.log
  *.sql
  *.sqlite

  # OS generated files #
  ######################
  .DS_Store
  .DS_Store?
  ._*
  .Spotlight-V100
  .Trashes
  ehthumbs.db
  Thumbs.db
  desktop.ini

  # Temporary files #
  ###################
  *.bak
  *.swp
  *.swo
  *~
  *#
