- name: Ensure Docker Directory Exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_group }}"
    mode: 0755
  loop:
    - "{{ user_home }}/docker"
    - "{{ user_home }}/docker/mysql"
    - "{{ user_home }}/docker/postgres"
    - "{{ user_home }}/docker/mongo"
  tags:
    - dev
    - directories

- name: Copy Database Stack Containers
  template:
    src: "{{ item }}.compose.yml"
    dest: "{{ user_home }}/docker/{{ item }}/docker-compose.yml"
    owner: "{{ main_user }}"
    group: "{{ main_group }}"
    mode: 0644
  loop:
    - mongo
    - postgres
    - mysql
  tags:
    - dev
    - containers
