---
- name: Ensure Developer Directories are Present
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_group }}"
    mode: 0755
  loop:
    - "{{ dev_dir }}/haybytes"
    - "{{ dev_dir }}/repos"
    - "{{ dev_dir }}/pr"
    - "{{ dev_dir }}/zarchived"
    - "{{ user_home }}/docker"
  tags:
    - dev
    - directories
