---
- name: "Tmux: Tmux Plugin Manager"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ user_home }}/.tmux/plugins/tpm"
    update: no
  tags:
    - dev
    - tmux
    - tpm

- name: "Tmux: Tmuxifier Directory"
  ansible.builtin.git:
    repo: "https://github.com/jimeh/tmuxifier.git"
    dest: "{{ user_home }}/.tmuxifier"
    update: no
  tags:
    - dev
    - tmux
    - tmuxifier
