version: "3.7"
services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    networks:
      - mongodb_network
    environment:
      - "MONGO_INITDB_ROOT_USERNAME={{ dev_containers_mongo_user }}"
      - "MONGO_INITDB_ROOT_PASSWORD={{ dev_containers_mongo_password }}"
    ports:
      - "{{ dev_containers_mongo_port }}:27017"
    volumes:
      - mongodb_data_container:/data/db

  mongo_express:
    image: mongo-express
    networks:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
    ports:
      - "{{ dev_containers_mongo_express_port }}:8081"

volumes:
  mongodb_data_container:
    driver: local

networks:
  mongo_network:
    driver: bridge
