version: "3.8"
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - "POSTGRES_USER={{ dev_containers_postgres_user }}"
      - "POSTGRES_PASSWORD={{ dev_containers_postgres_password }}"
    ports:
      - "{{ dev_containers_postgres_port }}:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
    driver: local
