tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"
brew "ansible"
brew "ansible-lint"
brew "apr-util"
brew "autorestic"
brew "bash"
brew "bat"
brew "bfg"
brew "node"
brew "bitwarden-cli"
brew "btop"
brew "caddy"
brew "cfitsio"
brew "coreutils"
brew "crf++"
brew "ctop"
brew "dockutil"
brew "exa"
brew "ffmpeg"
brew "fftw"
brew "fx"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-cliff"
brew "go"
brew "golang-migrate"
brew "golangci-lint"
brew "goreleaser"
brew "gum"
brew "htop"
brew "hugo"
brew "iftop"
brew "ilmbase"
brew "libheif"
brew "liblqr"
brew "libomp"
brew "imagemagick"
brew "ipython"
brew "lefthook"
brew "lf"
brew "libexif"
brew "libgsf"
brew "libimagequant"
brew "libmatio"
brew "libproxy"
brew "librsvg"
brew "libspng"
brew "mas"
brew "mingw-w64"
brew "mozjpeg"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "nghttp2"
brew "nss"
brew "nvm"
brew "openslide"
brew "orc"
brew "pipx"
brew "poetry"
brew "postgresql", restart_service: true
brew "pre-commit"
brew "pyenv"
brew "ripgrep"
brew "rustup-init"
brew "sqldiff"
brew "stow"
brew "subversion"
brew "tmux"
brew "tree"
brew "wget"
brew "wireguard-go"
brew "yank"
brew "yarn"
brew "yq"
brew "zlib"
brew "zsh-autosuggestions"
brew "go-task/tap/go-task"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
cask "android-file-transfer", args: { appdir: "/Applications" }
cask "android-sdk"
cask "android-studio"
cask "authy", args: { appdir: "/Applications" }
cask "bartender"
cask "basictex", args: { appdir: "/Applications" }
cask "bettertouchtool"
cask "bitwarden", args: { appdir: "/Applications" }
cask "brave-browser", args: { appdir: "/Applications" }
cask "caffeine"
cask "chromedriver", args: { appdir: "/Applications" }
cask "dash", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "firefox", args: { appdir: "/Applications" }
cask "flutter", args: { appdir: "/Applications" }
cask "font-fira-code", args: { appdir: "/Applications" }
cask "font-fira-code-nerd-font", args: { appdir: "/Applications" }
cask "font-hack-nerd-font", args: { appdir: "/Applications" }
cask "goland"
cask "google-chrome", args: { appdir: "/Applications" }
cask "home-assistant", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "microsoft-auto-update", args: { appdir: "/Applications" }
cask "microsoft-office", args: { appdir: "/Applications" }
cask "private-internet-access"
cask "raycast"
cask "rider"
cask "slack", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "steam", args: { appdir: "/Applications" }
cask "tableplus"
cask "transmit"
cask "visual-studio-code"
cask "vlc", args: { appdir: "/Applications" }
cask "zoom", args: { appdir: "/Applications" }
